version: 02
phases:
  build:
    commands:
      -echo Entered the build phasse...
      -mvn clean package
    post_build:
      commands:
       -echo Build completed successfully
artifacts:
  files:
    - '**/*'
  discard-paths: yes
  